name: simple_invoice
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cloudinary_public: ^0.21.0
  document_file_save_plus: ^2.0.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  http: ^1.0.0
  image_picker: ^0.8.7+5
  intl: ^0.18.1
  open_filex: ^4.3.2
  path_provider: ^2.0.15
  pdf: ^3.10.4
  printing: ^5.11.0
  responsive_sizer: ^3.1.1
  shared_preferences: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  custom_lint: ^0.4.0
  riverpod_lint: ^1.3.2

flutter:
  uses-material-design: true

  assets:
    - assets/secrets.json